/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_fminresult_free: (a: number, b: number) => void;
export const __wbg_stopstatus_free: (a: number, b: number) => void;
export const __wbg_wasmcmaes_free: (a: number, b: number) => void;
export const fmin: (a: any, b: number, c: any, d: number) => [number, number, number];
export const fmin_builtin: (a: number, b: any, c: number, d: number) => [number, number, number];
export const fmin_restarts: (a: any, b: number, c: any, d: number) => [number, number, number];
export const fminresult_best_f: (a: number) => number;
export const fminresult_best_x: (a: number) => any;
export const fminresult_evals: (a: number) => number;
export const fminresult_evals_best: (a: number) => number;
export const fminresult_iterations: (a: number) => number;
export const fminresult_stds: (a: number) => any;
export const fminresult_xmean: (a: number) => any;
export const stopstatus_condition: (a: number) => number;
export const stopstatus_ftarget: (a: number) => number;
export const stopstatus_maxfevals: (a: number) => number;
export const stopstatus_stopped: (a: number) => number;
export const stopstatus_tolfun: (a: number) => number;
export const stopstatus_tolx: (a: number) => number;
export const wasm_cmaes_from_state: (a: any) => [number, number, number];
export const wasmcmaes_ask: (a: number) => any;
export const wasmcmaes_ask_flat: (a: number) => any;
export const wasmcmaes_dimension: (a: number) => number;
export const wasmcmaes_lambda: (a: number) => number;
export const wasmcmaes_new: (a: any, b: number, c: number) => number;
export const wasmcmaes_result: (a: number) => number;
export const wasmcmaes_stop_status: (a: number) => number;
export const wasmcmaes_tell: (a: number, b: any, c: any) => void;
export const wasmcmaes_tell_flat: (a: number, b: any) => void;
export const wasmcmaes_to_json_state: (a: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
